server:
  port: 7373
spring:
  liquibase:
    enabled: false
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        provider:
          facebook:
            user-info-uri: https://graph.facebook.com/me?fields=email,name,verified
        registration:
          google:
            client-id: 1011974249454-6gq0hr01gqh3cndoqnss5r69tkk2nd84.apps.googleusercontent.com
            client-secret: saDA6Cj60wipncFM-hzBD-C6
          facebook:
            client-id: 1234020186718741
            client-secret: 0c0abaf685a83e879e8e48b1167c96ab
lemon:
  admin:
    username: admin@example.com
    password: admin!

  application-url: http://localhost:3000
  jwt:
    secret: 27924159D8B777B9457245B231294A62
  cors:
    allowed-origins: '*'
